---
- hosts: production
  remote_user: BTuvi
  become: yes
  vars_files:
  - vars-production.yml
  become_method: sudo
  vars:
    temp_folder: /tmp
  tasks:
    #Restart app
    - include: tasks/restartapp.yml

    #Install prerequisites
    - include: tasks/prerequisites.yml

    #Install Node.js
    - include: tasks/nodejs.yml

    #Git clone to project
    - include: tasks/gitclone.yml

    #Add .env file
    - include: tasks/addEnvFile.yml

    #npm i
    - include: tasks/npmi.yml

    #InitDB
    - include: tasks/dbrun.yml

    # PM2 jobs
    - include: tasks/pm2job.yml
