USERNAME: 'BTuvi'

PGHOSTNAME: 'postgres-production.postgres.database.azure.com'
PGUSERNAMEE: 'BTuvi@postgres-production'
PGPASS: '1p2a3s4s!5bar6'

LB_PORT: '52.166.10.100'

OKTA_CLIENT_SECRET: 'anrXvlxx3Wld5m_GkSw7QMdQDGcMtJztLVJ5MiSI'
OKTA_CLIENT_ID: '0oa20a396cBtVBkFM5d7'
OKTA_ORG_URL: 'https://dev-89027222.okta.com'
