USERNAME: 'BTuvi'

PGHOSTNAME: 'bootcampdbserverstaging.postgres.database.azure.com'
PGUSERNAMEE: 'BTuvi@bootcampdbserverstaging'
PGPASS: '1p2a3s4s!5bar6'

LB_PORT: '20.71.255.57'

OKTA_CLIENT_SECRET: 'anrXvlxx3Wld5m_GkSw7QMdQDGcMtJztLVJ5MiSI'
OKTA_CLIENT_ID: '0oa20a396cBtVBkFM5d7'
OKTA_ORG_URL: 'https://dev-89027222.okta.com'
